### ISSUE TITLE
Github generated tarballs change randomly

### ISSUE THREAD

**Issue by bket** [funtoo/keychain#100]
As the title states, github generated tarballs can change at any point. This creates issues for packaging on systems like [OpenBSD ](https://marc.info/?l=openbsd-ports&m=151973450514279&w=2) ports. Would it be possible to get official tarballs created / attached to releases?

**Comment by angryvincent** [comment]
release tarballs can be found on:
https://build.funtoo.org/distfiles/keychain/

**Comment by bket** [comment]
Issue solved.
