### ISSUE TITLE
Question: Does this work on shared home directories?

### ISSUE THREAD

**Issue by Hoeze** [funtoo/keychain#115]
I'd like to use it on multiple servers / desktops with a shared home directory.
Could the shared home dir cause issues with keychain?

**Comment by chsnell** [comment]
Keychain, by default, creates shell files by hostname, which should alleviate any issues on shared home directories.  The underlying ssh-agent will only be available on the host where it is started, though, so you could end up with multiple agents across multiple machines lying around.

**Comment by Hoeze** [comment]
Thanks for the explanation
