### ISSUE TITLE
Add dbus service

### ISSUE THREAD

**Issue by mathstuf** [funtoo/keychain#12]
D-Bus is another service which would be convenient to control with keychain.

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker! :) Follow the action here: https://bugs.funtoo.org/browse/FL-1995

**Comment by danielrobbins** [comment]
This issue has been resolved. See resolution here: https://bugs.funtoo.org/browse/FL-1995
