### ISSUE TITLE
No locking when called several time in parallell

### ISSUE THREAD

**Issue by htgoebel** [funtoo/keychain#13]
I'm starting up keychain as port of my shell login-script. And I normally have a KDE "konsole" window containing several shell sub-windows (tabs).

Now when logging in, each shell processes the login-script (.bash_profil) and _each_ shell starts keychain. So I end up with six or even more keychain dialog-boxes in parallel.

I would appreciate if keychain would implement some locking to avoid this. Thanks!

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker! :) Follow the action here: https://bugs.funtoo.org/browse/FL-1994

**Comment by danielrobbins** [comment]
This issue has been resolved in the Funtoo Linux bug tracker. Closing on GitHub.
