### ISSUE TITLE
support looking up ssh-agent started by docker for mac

### ISSUE THREAD

**Issue by fawaf** [funtoo/keychain#131]
the ssh-agent that is started by docker for mac looks like the following
```
name        66685   0.0  0.0  4292708    244   ??  S     5:02PM   0:00.01 /usr/bin/ssh-agent -l
```

**Comment by mrl5** [comment]
hello @fawaf - if you'd like to report a bug kindly use https://bugs.funtoo.org/

you can also reach us on Discord - for more info check https://www.funtoo.org/Welcome
