### ISSUE TITLE
release tags

### ISSUE THREAD

**Issue by glensc** [funtoo/keychain#17]
please push out tags corresponding to cut points of releases

currently zero releases are present as no git tags have been pushed (created):
https://github.com/funtoo/keychain/releases

it would be interesting to see what changes have been made since last release, but as no tags are present, can't really see

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker! :) Follow the action here: https://bugs.funtoo.org/browse/FL-1993

**Comment by glensc** [comment]
yes, i would prefer all release tags (and i'm not going to create JIRA account to comment in FL-1993)

**Comment by danielrobbins** [comment]
That's fine, you can comment here. We do our bug management on JIRA, so importing them ensures they don't get ignored. I plan to do tags from now on. It looks like historically this was not done.
