### ISSUE TITLE
support for gnome keychain

### ISSUE THREAD

**Issue by glensc** [funtoo/keychain#18]
i would love if `keychain` supported inheriting gnome keyring variables.

my use scenario: i launch desktop session and it launches gnome keyring. now i ssh in to that machine, i would like to reuse that gnome-keyring session. for that it's needed to export `GNOME_KEYRING_CONTROL` variable, and perhaps `GNOME_KEYRING_PID` if intending to stop it

```
GNOME_KEYRING_CONTROL=/run/user/500/keyring-NK834z
GNOME_KEYRING_PID=1928
```

```
USER       PID  PGRP                  STARTED TT          VSZ   RSS STAT CMD
glen      1928  1868 Tue Jun 10 11:33:52 2014 ?        370056  5328 SLl  gnome-keyring-daemon --start
```

to start a new ageng you can invoke:

```
gnome-keyring-daemon --start
```

and maybe even specify components `--components=pkcs11,secrets,ssh,gpg`:

```
$ gnome-keyring-daemon --help
gnome-keyring-daemon: insufficient process capabilities, unsecure memory might get used
Usage:
  gnome-keyring-daemon [OPTION...] - The Gnome Keyring Daemon

Help Options:
  -h, --help                                  Show help options

Application Options:
  -s, --start                                 Start a dameon or initialize an already running daemon.
  -r, --replace                               Replace the daemon for this desktop login environment.
  -f, --foreground                            Run in the foreground
  -d, --daemonize                             Run as a daemon
  -l, --login                                 Run by PAM for a user login. Read login password from stdin
  -c, --components=pkcs11,secrets,ssh,gpg     The optional components to run
  -C, --control-directory                     The directory for sockets and control data
  -V, --version                               Show the version number and exit.
```

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker! :) Follow the action here: https://bugs.funtoo.org/browse/FL-1992

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/FL-2046

**Comment by glensc** [comment]
so why two tickets in Funtoo JIRA?

**Comment by danielrobbins** [comment]
A bug in the GitHub import code -- each new comment on GitHub adds a new "issue" to the API, resulting in a duplicate. Will fix in a bit.

**Comment by zuzzurro** [comment]
So, the issue has been imported twice in JIRA two years ago, and then nothing happened?
What's the status of this issue? I'm considering starting to use keychain, and I'd love to have this thing addressed..

**Comment by x48rph** [comment]
In my opinion , trying to integrate gnome-keyring support into keychain would make the script overly complicated with not much to gain.  I may reconsider if someone submits a pull request / patch that works but at this time I'm going decline
