### ISSUE TITLE
Inheriting GPG agent serving SSH keys does not work

### ISSUE THREAD

**Issue by mpurzynski** [funtoo/keychain#19]
Hello.

I use gpg-agent with --enable-ssh-support with keys on the yubikey (can be any smartcard compatible hardware).

keychain called like this

eval `keychain --eval --agents ssh gpg --inherit any`

does not inherit pid and sock of the gpg-agent (that's faking ssh-agent) and I can use only one of them at once, but not both.

Ideally keychain would inherit other already running agents and if there's no valid key in .ssh then it should ask them 'hey, maybe you can help with authentication to something I don't have key for'.

Reproducing it does not require any hardware, just an 'authenticating' gpg key exported to SSH format and a few lines in bash/zsh. Happy to provide them if you don't have already.

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker! :) Follow the action here: https://bugs.funtoo.org/browse/FL-1991

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/FL-2045

**Comment by angryvincent** [comment]
is this a problem with keychain-2.8.2?

**Comment by Konfekt** [comment]
As a non-expert, does this mean that keychain provides no way to use gpg-agent as ssh-agent by --enable-ssh-support ? Instead, to use keychain for ssh, ssh-agent must be used?

**Comment by mpurzynski** [comment]
That's how it looked like - I can't verify it anymore, I not longer use this setup.

**Comment by danielrobbins** [comment]
This issue has been resolved in the Funtoo Linux bug tracker. Closing on GitHub.
