### ISSUE TITLE
pid tracking no longer works for gnupg 2.1.0

### ISSUE THREAD

**Issue by doy** [funtoo/keychain#22]
The entire `GPG_AGENT_INFO` mechanism was apparently removed, and so starting gpg-agent no longer outputs anything that can be used to get the pid. I'm not sure what the fix here should be.

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker! :) Follow the action here: https://bugs.funtoo.org/browse/FL-1988

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/FL-2039

**Comment by emlun** [comment]
master (c24ec771cf991b9a2db8a087222460cbc04d9387) seems to work for me in Arch now:

     * keychain 2.7.2_beta1 ~ http://www.funtoo.org
     * Found existing gpg-agent: X
     * Found existing ssh-agent: Y

    gpg (GnuPG) 2.1.1
    libgcrypt 1.6.2
    Copyright (C) 2014 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.

    Home: ~/.gnupg
    Supported algorithms:
    Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
    Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
            CAMELLIA128, CAMELLIA192, CAMELLIA256
    Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
    Compression: Uncompressed, ZIP, ZLIB, BZIP2

[Here][aur]'s a PKGBUILD in case any Arch users see this.

[aur]: https://aur.archlinux.org/packages/keychain-git

**Comment by danielrobbins** [comment]
This issue has been resolved in the Funtoo Linux bug tracker. Closing on GitHub.
