### ISSUE TITLE
Keychain requires public key to always be private key plus ".pub"

### ISSUE THREAD

**Issue by cbutterfield** [funtoo/keychain#3]
In my environment, we generally use a suffix for ALL PKI related files, including the private key (e.g. .pub, .pem, .ppk, etc).  This confuses keychain which spits out a warning and then fails.

My first take at fixing this on my system was to add additional logic to strip off the last file suffix if the first approach failed.  This seemed okay for my purposes, and perhaps others too.  But perhaps it would be more robust to match on either a signature OR a filename, so that regardless of the name (or even existance) of the public key, one could still proceed reasonably.  Comments?

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker! :) Follow the action here: https://bugs.funtoo.org/browse/FL-1998

**Comment by danielrobbins** [comment]
This issue has been resolved in the Funtoo Linux bug tracker. Closing on GitHub.
