### ISSUE TITLE
GPGTools (OS X)

### ISSUE THREAD

**Issue by andschwa** [funtoo/keychain#30]
Hi,

I'm using Keychain like this in my `.bashrc`

```
eval `keychain --inherit any --eval id_rsa A84A216F`
```

I use [GPGTools'](https://gpgtools.org/) GPG Suite Beta 5 on OS X Yosemite.

Keychain's start command for `gpg-agent` is

```
start_out=`gpg-agent --daemon $start_gpg_timeout 2>/dev/null`
```

However, `/usr/local/MacGPG2/bin/gpg-agent` returns exit code 2 if launched with `--daemon` and the agent was already running ("a gpg-agent is already running - not starting a new one"). (It returns exit code 0 if launched as just `gpg-agent`, but I don't think this is the solution).

I believe Keychain expects this return code to be 0, and so errors before attempting to load my GPG key.

I expected Keychain to detect that `gpg-agent` was already and continue loading, not for it to error.

I think I have a fix, which is to accept exit code 2 in addition to 0, but am unsure how that affects other platforms. I'll submit a PR shortly.

**Comment by andschwa** [comment]
All right. Nevermind about the PR, the prior issue does not manifest on master. However, it fails to find my GPG key, though it finds the SSH keys.

```
 * keychain ##VERSION## ~ http://www.funtoo.org
 * Inheriting ssh-agent (forwarded)
 * Warning: can't find A84A216F; skipping
 * Known ssh key: /Users/andrew/.ssh/id_rsa
```

Adding `--agents ssh,gpg` to my the initialization solved my problem, but this is against what the Keychain wiki said to do (remove `--agent ssh` entirely and it'll default to SSH and GPG).

```
* Inheriting ssh-agent (forwarded)
* Inheriting gpg-agent (1046)
* Known ssh key: /Users/andrew/.ssh/id_rsa
* Known gpg key: A84A216F
```

**Comment by andschwa** [comment]
Strangely, after restarting, a clean build from master is exhibiting the issue.

Using `keychain --inherit any --eval --agents ssh,gpg id_rsa A84A216F` in my shell profile:

## Before
```
 * keychain 2.7.2_beta1 ~ http://www.funtoo.org
 * Inheriting ssh-agent (forwarded)
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.4TcEwWKgIt/Listeners; export SSH_AUTH_SOCK;

 * Starting gpg-agent...
 * Error: Failed to start gpg-agent
 * Warning: can't find A84A216F; skipping
 * Known ssh key: /Users/andrew/.ssh/id_rsa
```
## After
```
 * keychain 2.7.2_beta1 ~ http://www.funtoo.org
 * Inheriting ssh-agent (forwarded)
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.4TcEwWKgIt/Listeners; export SSH_AUTH_SOCK;

 * Starting gpg-agent...


 * Known ssh key: /Users/andrew/.ssh/id_rsa
 * Known gpg key: A84A216F
```

**Comment by andschwa** [comment]
I may have found the problem, and if so, may also have found the solution. Please advise.

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/FL-2192

**Comment by andschwa** [comment]
Thanks @danielrobbins

**Comment by danielrobbins** [comment]
This issue has been resolved in the Funtoo Linux bug tracker. Closing on GitHub.

**Comment by gretel** [comment]
old issue but i ran into this issue and couldnt solve it by reading through all the references.
in the end i had to _remove_ the redirection put in place for cosmetic purposes:
```
> "/dev/null" 2>&1
```
from my `config.fish` file to let keychain finally find the key and ask for the passphrase.
