### ISSUE TITLE
ps: illegal argument: userid (gpg agent)

### ISSUE THREAD

**Issue by gour** [funtoo/keychain#41]
Hello, 

after moving from Linux to Free/PC-BSD I have problem invoking gpg-agent via keychain, iow. when I try:

```
gour@atmarama ~> keychain --eval -Q 52B5C810 | source

 * keychain 2.8.0 ~ http://www.funtoo.org
 * Starting ssh-agent...
 * Warning: can't find 52B5C810; skipping
```

although the above key is present and pinentry-gtk-2 dialog is invoked when I e.g. launch Emacs where it 's required by mu4e client

I also noticed that the problem might be with the following:
  
```
gour@atmarama ~> keychain --agents gpg,ssh

 * keychain 2.8.0 ~ http://www.funtoo.org
ps: illegal argument: gour
usage: ps [-aCcdefHhjlmrSTuvwXxZ] [-O fmt | -o fmt] [-G gid[,gid...]]
          [-J jid[,jid...]] [-M core] [-N system]
          [-p pid[,pid...]] [-t tty[,tty...]] [-U user[,user...]]
       ps [-L]
 * Starting gpg-agent...
 * Starting ssh-agent...
```

Let me say that I use fish-shell and trying to invoke keychain with:

```
# Keychain
if status --is-interactive
   keychain --eval --quiet -Q id_rsa | source
   keychain --eval --quiet -Q 52B5C810 | source
end
```

Any hint what might be the problem?

**Comment by gour** [comment]
I submitted PR to the FreeBSD showing it is some syntax error: see https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=200982

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/FL-2553

**Comment by danielrobbins** [comment]
Please attach the output of the command "uname".

**Comment by gour** [comment]
> Please attach the output of the command "uname".

Too late...in the meantime I returned back to Debian...

**Comment by danielrobbins** [comment]
This issue has been resolved in the Funtoo Linux bug tracker. Closing on GitHub.
