### ISSUE TITLE
No way to story passphrase for www-data

### ISSUE THREAD

**Issue by peteroconnor** [funtoo/keychain#7]
It seems that I am only able to story the passphrase throught "su - username", but not through "sudo -u username bash ...".

Therefore, it seems that there is no way for me to story the passphrase for www-data, so that a cgi script called by apache can keylessly access a remote server through ssh.

Is my understanding correct?

```bash
sudo -u www-data -H bash -c 'keychain $HOME/.ssh/id_rsa; bash $HOME/.keychain/$HOSTNAME-sh'
```
enter passphrase...

```bash
sudo -u www-data ssh host1
```
it will ask for the passphrase for id_rsa.

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker! :) Follow the action here: https://bugs.funtoo.org/browse/FL-1996

**Comment by danielrobbins** [comment]
You should be able to initialize keychain prior to starting apache, so that apache inherits the proper agent environment settings, and then it should work.
