### ISSUE TITLE
Incorrect handling of IdentitiesOnly

### ISSUE THREAD

**Issue by XenGi** [funtoo/keychain#82]
# What I did

Here's my sample config (`~/.ssh/config`):

```
Host example
    HostName example.com
    User bob
    IdentityFile ~/.ssh/id_rsa_2
    IdentitiesOnly yes
```

In `~/.ssh/`are 2 key files (`~/.ssh/id_rsa` and `~/.ssh/id_rsa_2`). keychain is started with `eval (keychain --eval id_rsa id_rsa_2)`.

# What should happen

```
$ ssh example
example:~ $
```

# What happens instead

```
$ ssh -v example
OpenSSH_7.5p1, OpenSSL 1.1.0f  25 May 2017
debug1: Reading configuration data /home/user/.ssh/config
[...]
debug1: Found key in /home/bob/.ssh/known_hosts:1
Host key fingerprint is SHA256:vT2c7AqO9hG107.....
[...]
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /home/bob/.ssh/id_rsa
Received disconnect from 192.168.0.555 port 22:2: Too many authentication failures for bob
Authentication failed.
```

# Final thoughts

From the ssh_config man page:

>      IdentitiesOnly
>              Specifies that ssh(1) should only use the authentication identity and certificate files explicitly configured in the
>              ssh_config files or passed on the ssh(1) command-line, even if ssh-agent(1) or a PKCS11Provider offers more identi‐
>              ties.  The argument to this keyword must be yes or no (the default).  This option is intended for situations where
>              ssh-agent offers many different identities.

I think keychain doesn't correctly handle this config setting. It should try the given key first and no other key but instead it falls back to default behavior and tries all known keys.
To me this looks like a bug.

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/FL-3956

**Comment by danielrobbins** [comment]
This behavior is related to ssh -- keychain is not involved at all in the flow you demonstrate.

**Comment by XenGi** [comment]
But it still looks like it has something todo with ether keychain itself or ssh-agent: https://gist.github.com/XenGi/8e9a260fa238c725cfa3fe4e977e4805
