### ISSUE TITLE
Is 2.8.4 the latest official release?

### ISSUE THREAD

**Issue by pvital** [funtoo/keychain#90]
Hello. This is more a question than an issue.

The Keychain package in Debian is orphan and I'm planning to adopt it. The latest release of Debian is 2.8.2, the same listed on official website https://www.funtoo.org/Keychain 

I'd like to know if the 2.8.4 is the really latest one. If so, I'll adopt the package in Debian community and upgrade to this new release at the same time.

**Comment by angryvincent** [comment]
yes, 2.8.4 is the latest release so far.

**Comment by pvital** [comment]
Great!
I'll submit a new package to Debian shipping this version.
