### ISSUE TITLE
keychain "forgets" the gpg passphrase

### ISSUE THREAD

**Issue by dinojr** [funtoo/keychain#91]
I'm running keychain with:
```eval `keychain --eval --agents ssh,gpg id_rsa myGPGkey` ```
from a shell script.
I can then provide my passphrase for ssh and gpg but after a while (in the same session) gpg-agent seems to have dropped the key (gpg fails to decrypt a file from within Emacs for instance) and I have to run my keychain command again, and provide the gpg passphrase once more. How could I investigate the cause of this problem ?

**Comment by apinsard** [comment]
By default the GPG agent caches the key for 600 seconds. You can increase this in your `~/.gnupg/gpg-agent.conf` :

    default-cache-ttl 84000
    max-cache-ttl 84000

I think `84000` is the max you can set, above it will be ignored. No idea why though.

**Comment by dinojr** [comment]
Antoine Pinsard <notifications@github.com> writes:

> By default the GPG agent caches the key for 600 seconds. You can increase this in your `~/.gnupg/gpg-agent.conf` :
>
>     default-cache-ttl 84000
>     max-cache-ttl 84000
>
> I think `84000` is the max you can set, above it will be ignored. No idea why though.

I should have thought of that... For some reason it's not on the funtoo
keychain page even though this default setting defeats the whole purpose
of keychain :-) I've set it up to 84000, so far it seems to have fixed
my problem. Thanks a lot.

Julien.

**Comment by x48rph** [comment]
Thanks for the report and fix. I added the gpg cache info to the Funtoo Keychain page.
