### ISSUE TITLE
/usr/bin/keychain: [[: not found

### ISSUE THREAD

**Issue by soulawaker** [funtoo/keychain#95]
I've installed version `2.8.1` from Ubuntu 16.04 apt.
Then I've tried following code in my `.zshrc`.
```
# keychain directory
[ -z "$HOSTNAME" ] && HOSTNAME=`uname -n`
[ -f $HOME/.keychain/$HOSTNAME-sh ] && \
. $HOME/.keychain/$HOSTNAME-sh

# keychain setting
eval `keychain --eval --confhost --agents ssh`
```
Then following error occurred when sourcing it.
```
/usr/bin/keychain: 1137: /usr/bin/keychain: [[: not found
/usr/bin/keychain: 1140: /usr/bin/keychain: [[: not found
/usr/bin/keychain: 1137: /usr/bin/keychain: [[: not found
/usr/bin/keychain: 1140: /usr/bin/keychain: [[: not found
...
(same message repeated)
```

**Comment by x48rph** [comment]
Thanks for the report. This is due to the use of [[ at the time which is bash specific. It has been fixed in later versions so you will need to either upgrade to a newer one or backport the changes

**Comment by soulawaker** [comment]
Ok. I will install latest version manually because it does not exist Ubuntu repo. I think I need to place only `keychain` and `keychain.1` to original keychain path. Is it right?

**Comment by soulawaker** [comment]
Never mind. I found what I need.
